// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4PTSswCmUG1vd0P5sb2BZxN8Wt5jJFI',
    appId: '1:304157965022:web:47ae62def2b5b578f6604f',
    messagingSenderId: '304157965022',
    projectId: 'health-tracker-coderower',
    authDomain: 'health-tracker-coderower.firebaseapp.com',
    storageBucket: 'health-tracker-coderower.firebasestorage.app',
    measurementId: 'G-Z7KQVJ7ZEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMt2ugDegZ1xzdOEOY856DZWV5lQ3csgM',
    appId: '1:304157965022:android:aca3ef0773f24010f6604f',
    messagingSenderId: '304157965022',
    projectId: 'health-tracker-coderower',
    storageBucket: 'health-tracker-coderower.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqyKnME3B9iI6vNDvscKxL9wWYB_uWEE',
    appId: '1:304157965022:ios:b24ebafc89d981d6f6604f',
    messagingSenderId: '304157965022',
    projectId: 'health-tracker-coderower',
    storageBucket: 'health-tracker-coderower.firebasestorage.app',
    iosBundleId: 'com.example.dailyHealthtrackerCoderower',
  );
}
